### ISSUE TITLE
How to install??

### ISSUE THREAD

**Issue by kick317** [Ocraz/clio#1]
I just read the README.md, i can't understand the instructions how to install??

**Comment by Zarcolio** [comment]
Hi @kick317 
I've added a requirements.txt file and instructions to README.md.
Does this work for you?
I've split all scripts into their own repo.

Also, I would recommend using https://github.com/Zarcolio/2ulb on all scripts for easy of use using symbolic links.

**Comment by kick317** [comment]
Thanks :)
